### ISSUE TITLE
OBCs issue

### ISSUE THREAD

**Issue by milicak** [mom-ocean/MOM6#623]
Hi,

I am using MOM6 commit aed7f0fca1b.
I have a problem and I hope somebody can help me.
I am trying to set up a wetting and drying case using MOM6.
This is a 1 layer BT case with an initial wave height. I just would like to see the wave run up on the coast.

I did this in GOLD recently, and what I did the following; after hacking the code;
I remove the minimum depth option in the code (GOLD), so that G%D can be positive (ocean) and negative (land).
I hacked the masking routine, so that if I set up a minus value (assume -5), then the wet points will be set up to that depth.
In a sense the code will think that -4.5 meter G%D is an ocean point. 
And finally I set an angstrom thickness for those points.
This works fine in GOLD, I can see nice run up;

However I moved everything to MOM6, and if I run the code with minimum_depth positive (in a sense no wetting drying mode), simulation is OK.
But If I run with similar to what I did to GOLD, then I get the following error;
NaN in input field of reproducing_sum(_3d).

This error is coming from reprodcing_sum routine.
It is due to NaN_error option.

When I run the code in debug mode, I see the NaNs first show up after OBC routine;
FATAL from PE     0: NaN detected: u BT [uv]hbt just after OBC

Thanks,
Mehmet

**Comment by kshedstrom** [comment]
Hi Mehmet,

Can you please send me your setup? There are changes in the queue which may
or may not help with this and it would be good to have a wetting and drying
case for us to test.

Kate

**Comment by milicak** [comment]
Hi,

I attached the routines that I changed, mostly if you search "Mehmet", 
you can find it.
if you need my initial conditions as netcdf files, let me know, I can 
provide those as well.

Best,
Mehmet

**Comment by kshedstrom** [comment]
Did you attach something? I don't see any attachments.

Did you set REENTRANT_X = False? I have to for most domains.

Kate

**Comment by adcroft** [comment]
Forwarding from mom google user group. This looks like the copying of grid
types might be a general problem for OBCs, not just this particular use
case?

---------- Forwarded message ----------
From: Mehmet Ilicak <ilicakme@gmail.com>
Date: Thu, Oct 5, 2017 at 1:00 AM
Subject: Re: [mom-model-users] wetting and drying in GOLD vs MOM6
To: MOM Users Mailing List <mom-users@googlegroups.com>


Here is the issue in new MOM6 for this particular case;

1) MOM6 creates the grid namely dG structure,
2) there is the halo update.
3) OBCs initilization called, this is crucial because it sets new depth
variables here; for instance if the western boundary is open G%bathyt(i,j)
= G%bathyt(i+1,j), so that two grid points on the boundary is equal to each
 other.
Up to here it is exactly like GOLD, but
4) now there is a new routine MOM_transcribe_grid and so called dynamic
grid (dG) is copied to regular grid G.
However, in that routine (copy_dyngrid_to_MOM_grid), after G%bathyt =
dG%bathyt, there is an halo update (line 128), and this messes up all the
steps done in 3.

Now two grid points next to each other are not same, in fact it copies to
eastern border bath to west halos, and that goes to compute cg_u =
sqrt(d(i,j)+d(i+1,j), and
I let the Depth be negative (land points), this leads to NaN.

I hope this helps.
Mehmet


--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by MJHarrison-GFDL** [comment]
I'm not sure why the halo update is over-writing the values outside the domain - as @kshedstrom indicted, unless REENTRANT_XY = True it shouldn't touch those values.

**Comment by milicak** [comment]
Hi,

Yes it was Reentrant_x = true in my case,
I tried with Reentrant_x = false and it works now.
So maybe a warning would be nice (maybe it is there but I missed it), so 
that when somebody has OBCs, they should set this to false.

Cheers,
Mehmet

**Comment by milicak** [comment]
[functions.zip](https://github.com/NOAA-GFDL/MOM6/files/1360378/functions.zip)

I add my files just in case if you need them.

**Comment by kshedstrom** [comment]
Yes, a regional modeler will consider the default reentrant choice to be quite odd.

There's also a lingering issue with the winds being reentrant when the domain is reentrant - the Arctic will demand reentraint winds with a "normal" (non-reentrant) domain.

**Comment by milicak** [comment]
Hi again,

I am not sure the new issue is related to OBCs or not but I am getting the following error;

h-point: mean=   0.0000000000000000E+00 min=   0.0000000000000000E+00 max=   0.0000000000000000E+00 After set forcing fluxes%buoy
h-point: c=         0 After set forcing fluxes%buoy
Fatal error in MPI_Recv: Message truncated, error stack:
MPI_Recv(224): MPI_Recv(buf=0x2acddba51c10, count=7550, dtype=0x4c000829, src=5, tag=1, MPI_COMM_WORLD, status=0x1c116d0) failed
do_cts(649)..: Message truncated; 120000 bytes received but buffer size is 60400

if I run the model with OBCs and 16 or 32 processors (the code is 800x200 in x and y direction).
However the same code runs without OBCs with 32 processors and also it runs with OBCs and 8 processors only. So it is weird to me the code blows up when I increase the number of processors. 
Any ideas?

Thanks in advance,
Mehmet

**Comment by adcroft** [comment]
Is this a configuration we can try?

**Comment by milicak** [comment]
Hi,

I attached the MOM_input and also the link of the netcdf files, let me know if you need my f90 routines. I changed couple of things but those shouldn't make any issues like this. I am using symmetric memory.

Netcdf files links;
https://www.dropbox.com/s/ofwn94szqovi975/Marmara_Sea_mosaicN600M200.nc?dl=0https://www.dropbox.com/s/y3tr4hkc021fajy/Marmara_Sea_mosaicN600M200_hini.nc?dl=0
[MOM_input.txt](https://github.com/NOAA-GFDL/MOM6/files/1566723/MOM_input.txt)

**Comment by MJHarrison-GFDL** [comment]
@milicak . Is this still an issue with the latest code? If so, we'll try to tackle this with more testing.

**Comment by Hallberg-NOAA** [comment]
@milicak, as far as we can tell, this issue may have been resolved with the latest version of the OBC code, so we are closing this issue.  Please feel free to reopen it with specifics if you are still encountering problems.
