### ISSUE TITLE
Output longitude on tri-polar fold is inconsistent with input grid

### ISSUE THREAD

**Issue by adcroft** [mom-ocean/MOM6#673]
@jiandewang noticed that the diagnosed longitude along the top edge of a tri-polar domain are not consistent. 

![image](https://user-images.githubusercontent.com/5859571/34055974-65269c40-e19f-11e7-888e-6932b261cf5d.png)

I don't believe it changes answers but it would be nice for ferret users to have the correct values.

**Comment by Hallberg-NOAA** [comment]
This behavior can be avoided by setting `USE_TRIPOLAR_GEOLONB_BUG = False` in the MOM_input and SIS_input files.
The runtime parameter `USE_TRIPOLAR_GEOLONB_BUG` was added on September 8, 2018, as a part of PR #851, and the default has been False (i.e., avoid this behavior) since June 7, 2020, as a part of PR #1127.
